// GEDCOM-generated NPC data — 130 Van Duynhoven individuals
export const NPC_DATA = {
  0: [
    {name:"Petrus Johannes van Duijnhoven",given:"Petrus",year:"31 MAR 1748",by:1748,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Petrus van Duijnhoven — born 31 MAR 1748, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joannes Peter van Duijnhoven",given:"Joannes",year:"ABT 1722",by:1722,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Joannes van Duijnhoven — born ABT 1722, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus Jansen van Duijnhoven",given:"Petrus",year:"15 MAR 1679",by:1679,place:"Aarle-Rixtel",sex:"M",gen:-4,item:null,
     lines:["Goede dag! I am Petrus van Duijnhoven, born around 15 MAR 1679 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"1678",by:1678,place:"Aarle-Rixtel",sex:"M",gen:-4,item:null,
     lines:["Goede dag! I am Johannes van Duijnhoven, born around 1678 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Godefridus van Duijnhoven",given:"Godefridus",year:"1681",by:1681,place:"Aarle-Rixtel",sex:"M",gen:-4,item:null,
     lines:["Goede dag! I am Godefridus van Duijnhoven, born around 1681 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joanna van Duijnhoven",given:"Joanna",year:"1683",by:1683,place:"Aarle-Rixtel",sex:"F",gen:-4,item:null,
     lines:["Goede dag! I am Joanna van Duijnhoven, born around 1683 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Ida van Duijnhoven",given:"Ida",year:"1686",by:1686,place:"Aarle-Rixtel",sex:"F",gen:-4,item:null,
     lines:["Goede dag! I am Ida van Duijnhoven, born around 1686 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"1720",by:1720,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Johannes van Duijnhoven — born 1720, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Jacobus van Duijnhoven",given:"Jacobus",year:"ABT 1722",by:1722,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Jacobus van Duijnhoven — born ABT 1722, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonius van Duijnhoven",given:"Antonius",year:"1727",by:1727,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Antonius van Duijnhoven — born 1727, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"1750",by:1750,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Johannes van Duijnhoven — born 1750, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Anna Maria van Duijnhoven",given:"Anna",year:"1752",by:1752,place:"Uden",sex:"F",gen:-2,item:null,
     lines:["Good day! Anna van Duijnhoven — born 1752, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonia van Duijnhoven",given:"Antonia",year:"1754",by:1754,place:"Uden",sex:"F",gen:-2,item:null,
     lines:["Good day! Antonia van Duijnhoven — born 1754, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes Peter van Duijnhoven",given:"Johannes",year:"1757",by:1757,place:"Uden",sex:"M",gen:-2,item:null,
     lines:["Good day! Johannes van Duijnhoven — born 1757, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Jan Dircx van Duijnhoven",given:"Jan",year:"ABT 1645",by:1645,place:"Aarle-Rixtel",sex:"M",gen:-6,item:null,
     lines:["Goede dag! I am Jan van Duijnhoven, born around ABT 1645 in Aarle-Rixtel.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duynhoven",given:"Johannes",year:"1539",by:1539,place:"Aarle-Rixtel",sex:"M",gen:-8,item:{id:"seal",icon:"🪙",name:"Family Seal",desc:"Needed for the next portal."},
     lines:["Ik ben Johannes van Duijnhoven, geboren omstreeks 1539.","Our family farms the heathlands of Noord-Brabant. Catholic folk, steadfast in faith.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Adrianus van Duijnhoven",given:"Adrianus",year:"ABT 1783",by:1783,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Adrianus van Duijnhoven — born ABT 1783, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus van Duijnhoven",given:"Petrus",year:"ABT 1785",by:1785,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Petrus van Duijnhoven — born ABT 1785, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Godefridus van Duijnhoven",given:"Godefridus",year:"ABT 1787",by:1787,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Godefridus van Duijnhoven — born ABT 1787, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus van Duijnhoven",given:"Gerardus",year:"1790",by:1790,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Gerardus van Duijnhoven — born 1790, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"1793",by:1793,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Johannes van Duijnhoven — born 1793, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Lambertus van Duijnhoven",given:"Lambertus",year:"1795",by:1795,place:"Uden",sex:"M",gen:-1,item:null,
     lines:["Good day! Lambertus van Duijnhoven — born 1795, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Dirck Janssen van Duynhoven",given:"Dirck",year:"ABT 1569",by:1569,place:"Aarle-Rixtel ar",sex:"M",gen:-7,item:null,
     lines:["Ik ben Dirck van Duijnhoven, geboren omstreeks ABT 1569.","Our family farms the heathlands of Noord-Brabant. Catholic folk, steadfast in faith.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Jan Jansen van Duynhoven",given:"Jan",year:"1660",by:1660,place:"Aarle-Rixtel ar",sex:"M",gen:-5,item:null,
     lines:["Goede dag! I am Jan van Duijnhoven, born around 1660 in Aarle-Rixtel ar.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Thomas Diercx van Duijnhoven",given:"Thomas",year:"ABT 1485",by:1485,place:"",sex:"M",gen:-10,item:null,
     lines:["Ik ben Thomas van Duijnhoven, geboren omstreeks ABT 1485.","Our family farms the heathlands of Noord-Brabant. Catholic folk, steadfast in faith.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Dirck van Duijnhoven",given:"Dirck",year:"ABT 1510",by:1510,place:"",sex:"M",gen:-9,item:null,
     lines:["Ik ben Dirck van Duijnhoven, geboren omstreeks ABT 1510.","Our family farms the heathlands of Noord-Brabant. Catholic folk, steadfast in faith.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  1: [
  ],
  2: [
    {name:"Petrus van Duijnhoven",given:"Petrus",year:"27 AUG 1799",by:1799,place:"Uden",sex:"M",gen:1,item:{id:"birth_record",icon:"📋",name:"Birth Record",desc:"Gen 1 proof of lineage."},
     lines:["Good day! Petrus van Duijnhoven — born 27 AUG 1799, Uden.","I work as Bouwman (yeoman farmer). The family has always been hardworking.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"1800",by:1800,place:"Uden",sex:"M",gen:1,item:null,
     lines:["Good day! Martinus van Duijnhoven — born 1800, Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendrik van Duijnhoven",given:"Hendrik",year:"ABT 1820",by:1820,place:"Uden",sex:"M",gen:1,item:null,
     lines:["Good day! Hendrik van Duijnhoven — born ABT 1820, Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joannes van Duijnhoven",given:"Joannes",year:"17 DEC 1797",by:1797,place:"Uden",sex:"M",gen:1,item:null,
     lines:["Good day! Joannes van Duijnhoven — born 17 DEC 1797, Uden.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"18 JAN 1798",by:1798,place:"Stiphout",sex:"F",gen:1,item:null,
     lines:["Good day! Johanna van Duijnhoven — born 18 JAN 1798, Stiphout.","Times change fast — revolution, new governments. But family endures through it all.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonia van Duijnhoven",given:"Antonia",year:"27 JAN 1800",by:1800,place:"Stiphout",sex:"F",gen:1,item:null,
     lines:["Good day! Antonia van Duijnhoven — born 27 JAN 1800, Stiphout.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  3: [
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"18 DEC 1829",by:1829,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Martinus van Duijnhoven, born 18 DEC 1829 in Uden.","I work as Akkerbouwer (arable farmer). The family has always been hardworking.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Marianus van Duijnhoven",given:"Marianus",year:"24 APR 1872",by:1872,place:"Uden",sex:"M",gen:3,item:{id:"train_ticket",icon:"🎫",name:"Train Ticket",desc:"Passage to Rotterdam."},
     lines:["Hello! I\'m Marianus van Duijnhoven, born 24 APR 1872 in Uden.","I work as Farmer/Agricultural worker. The family has always been hardworking.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Maria van Duijnhoven",given:"Maria",year:"27 MAY 1864",by:1864,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Maria van Duijnhoven, born 27 MAY 1864 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonius van Duijnhoven",given:"Antonius",year:"16 DEC 1865",by:1865,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Antonius van Duijnhoven, born 16 DEC 1865 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus Cornelus van Duijnhoven",given:"Petrus",year:"4 MAY 1863",by:1863,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Petrus van Duijnhoven, born 4 MAY 1863 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petronella van Duijnhoven",given:"Petronella",year:"1 JUN 1869",by:1869,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Petronella van Duijnhoven, born 1 JUN 1869 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"ABT 1870",by:1870,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born ABT 1870 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"1822",by:1822,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 1822 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Anna Maria van Duijnhoven",given:"Anna",year:"1823",by:1823,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Anna van Duijnhoven, born 1823 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petronella van Duijnhoven",given:"Petronella",year:"27 JUN 1825",by:1825,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Petronella van Duijnhoven, born 27 JUN 1825 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Henrica van Duijnhoven",given:"Henrica",year:"1833",by:1833,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Henrica van Duijnhoven, born 1833 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendricus van Duijnhoven",given:"Hendricus",year:"1837",by:1837,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Hendricus van Duijnhoven, born 1837 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"ABT 1832",by:1832,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Johannes van Duijnhoven, born ABT 1832 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"1828",by:1828,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Martinus van Duijnhoven, born 1828 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Anna Maria van Duijnhoven",given:"Anna",year:"1825",by:1825,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Anna van Duijnhoven, born 1825 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonius van Duijnhoven",given:"Antonius",year:"1826",by:1826,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Antonius van Duijnhoven, born 1826 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Wilhelmus van Duijnhoven",given:"Wilhelmus",year:"1828",by:1828,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Wilhelmus van Duijnhoven, born 1828 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Lamberdina van Duijnhoven",given:"Lamberdina",year:"1829",by:1829,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Lamberdina van Duijnhoven, born 1829 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joanna van Duijnhoven",given:"Joanna",year:"1831",by:1831,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Joanna van Duijnhoven, born 1831 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Ida van Duijnhoven",given:"Ida",year:"1831",by:1831,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Ida van Duijnhoven, born 1831 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Woutrina van Duijnhoven",given:"Woutrina",year:"1833",by:1833,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Woutrina van Duijnhoven, born 1833 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendricus van Duijnhoven",given:"Hendricus",year:"1834",by:1834,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Hendricus van Duijnhoven, born 1834 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joanna van Duijnhoven",given:"Joanna",year:"1836",by:1836,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Joanna van Duijnhoven, born 1836 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Anna Maria van Duijnhoven",given:"Anna",year:"1838",by:1838,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Anna van Duijnhoven, born 1838 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petronella van Duijnhoven",given:"Petronella",year:"1839",by:1839,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Petronella van Duijnhoven, born 1839 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Wilhelmus van Duijnhoven",given:"Wilhelmus",year:"1842",by:1842,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Wilhelmus van Duijnhoven, born 1842 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Lambertus van Duijnhoven",given:"Lambertus",year:"6 NOV 1861",by:1861,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Lambertus van Duijnhoven, born 6 NOV 1861 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Adriana van Duijnhoven",given:"Adriana",year:"1898",by:1898,place:"Netherlands",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Adriana van Duijnhoven, born 1898 in Netherlands.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendricus Petrus van Duijnhoven",given:"Hendricus",year:"1858",by:1858,place:"Uden",sex:"M",gen:2,item:null,
     lines:["Hello! I\'m Hendricus van Duijnhoven, born 1858 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Mechelina van Duijnhoven",given:"Mechelina",year:"1859",by:1859,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Mechelina van Duijnhoven, born 1859 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Maria Mechelina van Duijnhoven",given:"Maria",year:"1860",by:1860,place:"Uden",sex:"F",gen:2,item:null,
     lines:["Hello! I\'m Maria van Duijnhoven, born 1860 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendrica van Duijnhoven",given:"Hendrica",year:"1861",by:1861,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Hendrica van Duijnhoven, born 1861 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petronella van Duijnhoven",given:"Petronella",year:"ABT 1863",by:1863,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Petronella van Duijnhoven, born ABT 1863 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus van Duijnhoven",given:"Petrus",year:"1864",by:1864,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Petrus van Duijnhoven, born 1864 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus van Duijnhoven",given:"Petrus",year:"ABT 1870",by:1870,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Petrus van Duijnhoven, born ABT 1870 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"12 MAR 1875",by:1875,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 12 MAR 1875 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Willem van Duijnhoven",given:"Willem",year:"16 JUN 1867",by:1867,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Willem van Duijnhoven, born 16 JUN 1867 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Lambertus van Duijnhoven",given:"Lambertus",year:"20 JAN 1869",by:1869,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Lambertus van Duijnhoven, born 20 JAN 1869 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Ardina van Duijnhoven",given:"Ardina",year:"28 OCT 1870",by:1870,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Ardina van Duijnhoven, born 28 OCT 1870 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Adrianus van Duijnhoven",given:"Adrianus",year:"12 NOV 1871",by:1871,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Adrianus van Duijnhoven, born 12 NOV 1871 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendrica van Duijnhoven",given:"Hendrica",year:"2 FEB 1873",by:1873,place:"Uden",sex:"F",gen:3,item:null,
     lines:["Hello! I\'m Hendrica van Duijnhoven, born 2 FEB 1873 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Peter van Duijnhoven",given:"Peter",year:"21 JUN 1877",by:1877,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Peter van Duijnhoven, born 21 JUN 1877 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Franciscus van Duijnhoven",given:"Franciscus",year:"26 NOV 1879",by:1879,place:"Uden",sex:"M",gen:3,item:null,
     lines:["Hello! I\'m Franciscus van Duijnhoven, born 26 NOV 1879 in Uden.","The railway and factory whistle have changed everything. The old village ways are fading.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  4: [
    {name:"Francina van Duijnhoven",given:"Francina",year:"10 APR 1907",by:1907,place:"Boekel",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Francina van Duijnhoven, born 10 APR 1907 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"26 MAR 1908",by:1908,place:"Boekel",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Martinus van Duijnhoven, born 26 MAR 1908 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus van Duijnhoven",given:"Gerardus",year:"8 SEP 1909",by:1909,place:"Boekel",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Gerardus van Duijnhoven, born 8 SEP 1909 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hubertus van Duijnhoven",given:"Hubertus",year:"28 MAY 1911",by:1911,place:"Boekel",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Hubertus van Duijnhoven, born 28 MAY 1911 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Jan van Duijnhoven",given:"Jan",year:"9 MAY 1912",by:1912,place:"Boekel",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Jan van Duijnhoven, born 9 MAY 1912 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna Maria van Duijnhoven",given:"Johanna",year:"14 SEP 1913",by:1913,place:"Boekel",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 14 SEP 1913 in Boekel.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"26 SEP 1914",by:1914,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 26 SEP 1914 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johan van Duijnhoven",given:"Johan",year:"12 NOV 1915",by:1915,place:"Uden",sex:"M",gen:4,item:{id:"immigration_papers",icon:"📰",name:"Immigration Papers",desc:"Entry to America."},
     lines:["Hello! I\'m Johan van Duijnhoven, born 12 NOV 1915 in Uden.","I work as Farmer. The family has always been hardworking.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Antonius van Duijnhoven",given:"Antonius",year:"14 DEC 1916",by:1916,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Antonius van Duijnhoven, born 14 DEC 1916 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerarda Maria van Duijnhoven",given:"Gerarda",year:"25 SEP 1919",by:1919,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Gerarda van Duijnhoven, born 25 SEP 1919 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Marinus van Duijnhoven",given:"Marinus",year:"10 NOV 1920",by:1920,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Marinus van Duijnhoven, born 10 NOV 1920 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Hendrica Maria van Duijnhoven",given:"Hendrica",year:"23 MAY 1923",by:1923,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Hendrica van Duijnhoven, born 23 MAY 1923 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Josephus Antonius van Duijnhoven",given:"Josephus",year:"23 JAN 1905",by:1905,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Josephus van Duijnhoven, born 23 JAN 1905 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Joannes Petrus Paulus van Duijnhove",given:"Joannes",year:"29 JUN 1906",by:1906,place:"Helmond",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Joannes van Duijnhoven, born 29 JUN 1906 in Helmond.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus Petrus van Duijnhoven",given:"Gerardus",year:"29 NOV 1908",by:1908,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Gerardus van Duijnhoven, born 29 NOV 1908 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Adrianus Antonius van Duijnhoven",given:"Adrianus",year:"14 JUL 1909",by:1909,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Adrianus van Duijnhoven, born 14 JUL 1909 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Josina Maria van Duijnhoven",given:"Josina",year:"20 DEC 1910",by:1910,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Josina van Duijnhoven, born 20 DEC 1910 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna Maria van Duijnhoven",given:"Johanna",year:"6 SEP 1912",by:1912,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 6 SEP 1912 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Theodora Josephina van Duijnhoven",given:"Theodora",year:"31 MAY 1915",by:1915,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Theodora van Duijnhoven, born 31 MAY 1915 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus Hubertus van Duijnhoven",given:"Petrus",year:"14 APR 1917",by:1917,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Petrus van Duijnhoven, born 14 APR 1917 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Maria van Duijnhoven",given:"Maria",year:"29 DEC 1920",by:1920,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Maria van Duijnhoven, born 29 DEC 1920 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Louisa Antonia van Duijnhoven",given:"Louisa",year:"11 JAN 1923",by:1923,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Louisa van Duijnhoven, born 11 JAN 1923 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Geertruda van Duijnhoven",given:"Geertruda",year:"1901",by:1901,place:"Netherlands",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Geertruda van Duijnhoven, born 1901 in Netherlands.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martina van Duijnhoven",given:"Martina",year:"1903",by:1903,place:"Netherlands",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Martina van Duijnhoven, born 1903 in Netherlands.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Francisca van Duijnhoven",given:"Francisca",year:"1904",by:1904,place:"Netherlands",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Francisca van Duijnhoven, born 1904 in Netherlands.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Petrus Johannes van Duijnhoven",given:"Petrus",year:"4 DEC 1908",by:1908,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Petrus van Duijnhoven, born 4 DEC 1908 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johanna van Duijnhoven",given:"Johanna",year:"1911",by:1911,place:"Netherlands",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Johanna van Duijnhoven, born 1911 in Netherlands.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"1912",by:1912,place:"Netherlands",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Martinus van Duijnhoven, born 1912 in Netherlands.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus van Duijnhoven",given:"Gerardus",year:"31 AUG 1904",by:1904,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Gerardus van Duijnhoven, born 31 AUG 1904 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Martinus van Duijnhoven",given:"Martinus",year:"22 OCT 1905",by:1905,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Martinus van Duijnhoven, born 22 OCT 1905 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus van Duijnhoven",given:"Gerardus",year:"17 OCT 1906",by:1906,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Gerardus van Duijnhoven, born 17 OCT 1906 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Geertruda van Duijnhoven",given:"Geertruda",year:"30 SEP 1907",by:1907,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Geertruda van Duijnhoven, born 30 SEP 1907 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Gerardus Petrus van Duijnhoven",given:"Gerardus",year:"29 NOV 1908",by:1908,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Gerardus van Duijnhoven, born 29 NOV 1908 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"24 JAN 1910",by:1910,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Johannes van Duijnhoven, born 24 JAN 1910 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Ardina van Duijnhoven",given:"Ardina",year:"21 JUN 1912",by:1912,place:"Uden",sex:"F",gen:4,item:null,
     lines:["Hello! I\'m Ardina van Duijnhoven, born 21 JUN 1912 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Johannes van Duijnhoven",given:"Johannes",year:"6 APR 1914",by:1914,place:"Uden",sex:"M",gen:4,item:null,
     lines:["Hello! I\'m Johannes van Duijnhoven, born 6 APR 1914 in Uden.","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  5: [
    {name:"Morris Wilhelm Peter van Duynhoven",given:"Morris",year:"8 DEC 1951",by:1951,place:"Minnesota",sex:"M",gen:5,item:{id:"baseball_card",icon:"⚾",name:"Baseball Card",desc:"Lucky charm."},
     lines:["Hi! I\'m Morris van Duynhoven — born 8 DEC 1951 in Minnesota!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Wilhelmus Josephus van Duynhoven",given:"Wilhelmus",year:"5 MAR 1953",by:1953,place:"Minnesota",sex:"M",gen:5,item:null,
     lines:["Hi! I\'m Wilhelmus van Duynhoven — born 5 MAR 1953 in Minnesota!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Anna Maria van Duynhoven",given:"Anna",year:"19 DEC 1954",by:1954,place:"Minnesota",sex:"F",gen:5,item:null,
     lines:["Hi! I\'m Anna van Duynhoven — born 19 DEC 1954 in Minnesota!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Peter John van Duynhoven",given:"Peter",year:"24 APR 1956",by:1956,place:"Minnesota",sex:"M",gen:5,item:null,
     lines:["Hi! I\'m Peter van Duynhoven — born 24 APR 1956 in Minnesota!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Mary C. van Duynhoven",given:"Mary",year:"1959",by:1959,place:"Minnesota",sex:"F",gen:5,item:null,
     lines:["Hi! I\'m Mary van Duynhoven — born 1959 in Minnesota!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Carolyn Kay van Duynhoven",given:"Carolyn",year:"11 JUL 1957",by:1957,place:"Sibley Township",sex:"F",gen:5,item:null,
     lines:["Hi! I\'m Carolyn van Duynhoven — born 11 JUL 1957 in Sibley Township!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Deborah Gail Van Duynhoven",given:"Deborah",year:"18 SEP 1953",by:1953,place:"Greenwood",sex:"F",gen:5,item:null,
     lines:["Hi! I\'m Deborah van Duynhoven — born 18 SEP 1953 in Greenwood!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Maria Antonia Stephanie van Duijnho",given:"Maria",year:"25 JAN 1951",by:1951,place:"Uden",sex:"F",gen:5,item:null,
     lines:["Hi! I\'m Maria van Duynhoven — born 25 JAN 1951 in Uden!","From Aarle-Rixtel in 1539 to here — the Van Duynhoven name travels far!","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  6: [
    {name:"Charles van Duynhoven",given:"Charles",year:"13 SEP 1982",by:1982,place:"Minnesota",sex:"M",gen:6,item:null,
     lines:["Hi! I\'m Charles van Duynhoven — born 13 SEP 1982 in Minnesota!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Arthur van Duynhoven",given:"Arthur",year:"ABT 1984",by:1984,place:"Minnesota",sex:"M",gen:6,item:{id:"floppy_disk",icon:"💾",name:"Floppy Disk",desc:"Family tree in BASIC."},
     lines:["Hi! I\'m Arthur van Duynhoven — born ABT 1984 in Minnesota!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"William van Duynhoven",given:"William",year:"14 MAY 1987",by:1987,place:"Minnesota",sex:"M",gen:6,item:null,
     lines:["Hi! I\'m William van Duynhoven — born 14 MAY 1987 in Minnesota!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
  7: [
    {name:"Isabella van Duynhoven",given:"Isabella",year:"11 AUG 2009",by:2009,place:"St. Paul",sex:"F",gen:7,item:{id:"family_photo",icon:"📸",name:"Family Photo",desc:"All Gen-7 cousins!"},
     lines:["Hi! I\'m Isabella van Duynhoven — born 11 AUG 2009 in St. Paul!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Henry van Duynhoven",given:"Henry",year:"4 NOV 2014",by:2014,place:"St. Paul",sex:"M",gen:7,item:null,
     lines:["Hi! I\'m Henry van Duynhoven — born 4 NOV 2014 in St. Paul!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Charlotte van Duynhoven",given:"Charlotte",year:"25 APR 2016",by:2016,place:"Wisconsin",sex:"F",gen:7,item:null,
     lines:["Hi! I\'m Charlotte van Duynhoven — born 25 APR 2016 in Wisconsin!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Knoxley van Duynhoven",given:"Knoxley",year:"ABT 2021",by:2021,place:"St. Croix Falls",sex:"F",gen:7,item:null,
     lines:["Hi! I\'m Knoxley van Duynhoven — born ABT 2021 in St. Croix Falls!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Raven van Duynhoven",given:"Raven",year:"29 MAR 2017",by:2017,place:"Haarlem",sex:"X",gen:7,item:null,
     lines:["Hi! I\'m Raven van Duynhoven — born 29 MAR 2017 in Haarlem!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Starling van Duynhoven",given:"Starling",year:"16 JUL 2020",by:2020,place:"Haarlem",sex:"X",gen:7,item:null,
     lines:["Hi! I\'m Starling van Duynhoven — born 16 JUL 2020 in Haarlem!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Tenley van Duynhoven",given:"Tenley",year:"12 JAN 2019",by:2019,place:"St. Croix Falls",sex:"F",gen:7,item:null,
     lines:["Hi! I\'m Tenley van Duynhoven — born 12 JAN 2019 in St. Croix Falls!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
    {name:"Maxwell van Duynhoven",given:"Maxwell",year:"13 OCT 2018",by:2018,place:"St. Paul",sex:"M",gen:7,item:null,
     lines:["Hi! I\'m Maxwell van Duynhoven — born 13 OCT 2018 in St. Paul!","500 years of family history! We video-call cousins across the Atlantic. Incredible.","The Van Duynhoven name traces to Johannes, born 1539. Remember that name — it\'s where we all begin."]},
  ],
};

export const PORTAL_ITEMS = [null,"seal","prayer_book","birth_record","train_ticket","immigration_papers","baseball_card","floppy_disk"];
